# Generated by Django 2.2.1 on 2020-09-10 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeTentacleDamage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ViscidusPoisonTick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='一夜鱼龙舞', max_length=100)),
                ('damage', models.IntegerField(default=0)),
                ('hit', models.IntegerField(default=0)),
                ('tick', models.IntegerField(default=0)),
                ('uptime', models.FloatField(default=0.0)),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Fight')),
                ('friendly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Friendly')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.WCLLog')),
            ],
        ),
        migrations.CreateModel(
            name='BossNatureProtection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='一夜鱼龙舞', max_length=100)),
                ('nature_protection_absorb', models.IntegerField()),
                ('nature_protection_cast', models.IntegerField()),
                ('nature_protection_uptime', models.FloatField()),
                ('major_nature_protection_absorb', models.IntegerField()),
                ('major_nature_protection_cast', models.IntegerField()),
                ('major_nature_protection_uptime', models.FloatField()),
                ('importance', models.CharField(default='L3', max_length=20)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Enemy')),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Fight')),
                ('friendly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Friendly')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.WCLLog')),
            ],
        ),
    ]
