# Generated by Django 2.2.1 on 2020-08-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visciduspoisontick',
            name='name',
            field=models.CharField(default='一夜鱼龙舞', max_length=100),
        ),
    ]
