# Generated by Django 2.2.1 on 2020-09-02 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20200902_0337'),
        ('taq', '0002_visciduspoisontick_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossNatureProtection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_protection_absorb', models.IntegerField()),
                ('nature_protection_cast', models.IntegerField()),
                ('nature_protection_uptime', models.FloatField()),
                ('major_nature_protection_absorb', models.IntegerField()),
                ('major_nature_protection_cast', models.IntegerField()),
                ('major_nature_protection_uptime', models.BooleanField()),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Enemy')),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Fight')),
                ('friendly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Friendly')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.WCLLog')),
            ],
        ),
    ]
