# Generated by Django 2.2.1 on 2020-09-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taq', '0004_auto_20200902_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossnatureprotection',
            name='name',
            field=models.CharField(default='一夜鱼龙舞', max_length=100),
        ),
    ]
