# Generated by Django 2.2.1 on 2020-09-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taq', '0005_bossnatureprotection_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossnatureprotection',
            name='importance',
            field=models.CharField(default='L3', max_length=20),
        ),
    ]
