# Generated by Django 2.2.1 on 2020-08-28 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200827_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='wcllog',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 9, 32, 29, 873674)),
        ),
        migrations.AlterField(
            model_name='wcllog',
            name='code',
            field=models.CharField(default='wcl_code', max_length=50, unique=True, verbose_name='wcl report code'),
        ),
    ]
