# Generated by Django 2.2.1 on 2020-08-30 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200830_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcllog',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 7, 28, 6, 466250)),
        ),
    ]
