# Generated by Django 2.2.1 on 2020-09-02 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20200902_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcllog',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 2, 3, 53, 42, 112006)),
        ),
    ]
